# Generated by Django 6.0.2 on 2026-03-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swappy', '0002_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='swappy.student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
