# Generated by Django 6.0.2 on 2026-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swappy', '0004_connection_created_at_alter_notification_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
