# Generated by Django 6.0.2 on 2026-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swappy', '0005_connection_is_deleted_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
