# Generated by Django 6.0.2 on 2026-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swappy', '0006_student_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
